name: Report
on: push
jobs:
  Report_Upload:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Upload artifact
      uses: zoispag/action-s3-upload-artifact@v1
      id: s3
      with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: 7com1029
          bucket_root: Artifacts
          path: ./*

    
     
