name: Report
on: push
jobs:
  Report_Upload:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: zap_scan
          path: 7com1039-security/Archieves
      - name: Upload S3    
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 7com1029
          source_dir: 7com1039-security/Archieves   
      - name: Link To Report
        run: echo "https://s3.amazonaws.com/bucketName/${{steps.S3.outputs.object_key}}/"
