name: Implementing w/o Security
on: push
jobs:

 build-image-publish-to-dockerhub:
      runs-on: ubuntu-latest
      name: Create a Docker image and push it to DockerHub
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml      
      -  name: Logging in Dockerhub
         uses: docker/login-action@v2
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sanjid369/devops21073983:latest
            
      - name: Docker Push
        run: docker push sanjid369/devops21073983:latest

 
